import keyMirror from 'key-mirror'

export default keyMirror({
  SET_PLATFORM: null,
  SET_VERSION: null,

  SESSION_TOKEN_REQUEST: null,
  SESSION_TOKEN_SUCCESS: null,
  SESSION_TOKEN_FAILURE: null,

  DELETE_TOKEN_REQUEST: null,
  DELETE_TOKEN_SUCCESS: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  SET_SESSION_TOKEN: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  GET_PROFILE_REPOS: null,
  GET_PROFILE_REPOS_SUCCESS: null,
  GET_PROFILE_REPOS_FAIL: null,

  GET_PROFILE_REPO_INFO: null,
  GET_PRIFLE_REPO_INFO_SUCCESS: null,
  GET_PFOFILE_REPO_INFO_FAIL: null,

  GET_USER: null,
  GET_USER_SUCCESS: null,
  GET_USER_FAIL: null,

  GET_ID_NUMBER: null,
  GET_ID_NUMBER_SUCCESS: null,
  GET_ID_NUMBER_FAIL: null,

  GET_QRCODE: null,
  GET_QRCODE_SUCCESS: null,
  GET_QRCODE_FAIL: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null

})
